import Head from "next/head";
import { useEffect } from "react";
import Image from "next/image";
import Styles from "@/styles/index.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Bros Coffee | 兄弟咖啡</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>
      <section className={Styles.jumbotron}>
        <h1 className={Styles.jbTitle}>Bros Coffee</h1>
        <h4 className={Styles.jbText}>兄弟咖啡</h4>
      </section>
      <section className={Styles.story}>
        <div className={Styles.storyInfo}>
          <div className={Styles.title}>
            <p>品牌精神</p>
            <p>OUR STORY</p>
          </div>
          <div className={Styles.text}>
            <p>用咖啡開啟美好生活</p>
            <p>Have a nice day</p>
          </div>
        </div>
      </section>
    </>
  );
}
