import Head from "next/head";
import { useEffect, useState } from "react";
import Link from "next/link";
import Styles from "@/styles/index.module.css";
import { Swiper, SwiperSlide } from "swiper/react";
import ProductItem from "../../components/UI/productItem";
// Import Swiper styles
import "swiper/css";
import "swiper/css/pagination";
import "swiper/css/navigation";
// import required modules
import { Pagination, Navigation, Autoplay } from "swiper/modules";

export default function Home() {
  const [is1024, setIs1024] = useState({ width: undefined });

  // 監聽視窗大小
  useEffect(() => {
    const handleResize = () => {
      setIs1024({ width: window.innerWidth });
    };

    window.addEventListener("resize", handleResize);
    return () => window.removeEventListener("resize", handleResize);
  }, []);

  const smSlidePerView = is1024.width < 1024 ? true : false;

  return (
    <>
      <Head>
        <title>Bros Coffee | 兄弟咖啡</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>
      <section className={Styles.jumbotron}>
        <h1 className={Styles.jbTitle}>Bros Coffee</h1>
        <h4 className={Styles.jbText}>兄弟咖啡</h4>
      </section>
      <section className={Styles.story}>
        <div className={Styles.storyInfo}>
          <div className={Styles.title}>
            <p>品牌精神</p>
            <p>OUR STORY</p>
          </div>
        </div>
        <div className={Styles.text}>
          <p>用咖啡開啟美好生活</p>
          <p>Have a nice day</p>
        </div>
      </section>
      <section className={Styles.swiper}>
        <Swiper
          cssMode={true}
          slidesPerView={smSlidePerView ? 1 : 3}
          spaceBetween={30}
          navigation={true}
          allowTouchMove={true}
          loop={true}
          autoplay={{ delay: 5000 }}
          pagination={{
            clickable: true,
          }}
          modules={[Autoplay, Pagination, Navigation]}
          className={Styles.mySwiper}
        >
          <SwiperSlide>
            <Link href='/'>
              <img src='/大安門市.jpg' alt='' className={Styles.slideImg} />
            </Link>
          </SwiperSlide>
          <SwiperSlide>
            <Link href='/'>
              <img src='/台大門市.jpg' alt='' className={Styles.slideImg} />
            </Link>
          </SwiperSlide>
          <SwiperSlide>
            <Link href='/'>
              <img src='/市府門市.jpg' alt='' className={Styles.slideImg} />
            </Link>
          </SwiperSlide>
          <SwiperSlide>
            <Link href='/'>
              <img src='/瑞光門市.jpg' alt='' className={Styles.slideImg} />
            </Link>
          </SwiperSlide>
          <SwiperSlide>
            <Link href='/'>
              <img src='/高雄門市.jpg' alt='' className={Styles.slideImg} />
            </Link>
          </SwiperSlide>
          <SwiperSlide>
            <Link href='/'>
              <img src='/大安門市.jpg' alt='' className={Styles.slideImg} />
            </Link>
          </SwiperSlide>
          <SwiperSlide>
            <Link href='/'>
              <img src='/台大門市.jpg' alt='' className={Styles.slideImg} />
            </Link>
          </SwiperSlide>
          <SwiperSlide>
            <Link href='/'>
              <img src='/市府門市.jpg' alt='' className={Styles.slideImg} />
            </Link>
          </SwiperSlide>
          <SwiperSlide>
            <Link href='/'>
              <img src='/瑞光門市.jpg' alt='' className={Styles.slideImg} />
            </Link>
          </SwiperSlide>
          <SwiperSlide>
            <Link href='/'>
              <img src='/高雄門市.jpg' alt='' className={Styles.slideImg} />
            </Link>
          </SwiperSlide>
        </Swiper>
      </section>
      <section className={Styles.bgColour}>
        <h2 className={Styles.title}>產品介紹</h2>
      </section>
      <section className={Styles.product1}>
        {/* 兩個bcgimage交換 */}
        <div className={Styles.img}></div>
        <div className={Styles.info}>
          <ProductItem text='甜蜜烘焙 獨家風味' title='配方豆' bgc='#808080' link='/' />
          <ProductItem text='風味旅程 當季首選' title='單品豆' bgc='#4D4D4D' link='/' />
          <ProductItem text='出類拔萃 一時之選' title='極精品豆' bgc='#1A1A1A' link='/' />
        </div>
      </section>
      <div className={Styles.infosm}>
        <ProductItem text='甜蜜烘焙 獨家風味' title='配方豆' bgc='#808080' link='/' />
        <ProductItem text='風味旅程 當季首選' title='單品豆' bgc='#4D4D4D' link='/' />
        <ProductItem text='出類拔萃 一時之選' title='極精品豆' bgc='#1A1A1A' link='/' />
      </div>
      <section className={Styles.product2}>
        <div className={Styles.img}></div>
        <div className={Styles.info}>
          <ProductItem text='頂尖之作 餘韻不斷' title='行家系列' bgc='#808080' link='/' />
          <ProductItem text='狂銷熱賣 小資首選' title='經典系列' bgc='#4D4D4D' link='/' />
          <ProductItem text='繽紛風味 簡單享受' title='單品系列' bgc='#1A1A1A' link='/' />
        </div>
      </section>
      <div className={Styles.infosm}>
        <ProductItem text='頂尖之作 餘韻不斷' title='行家系列' bgc='#808080' link='/' />
        <ProductItem text='狂銷熱賣 小資首選' title='經典系列' bgc='#4D4D4D' link='/' />
        <ProductItem text='繽紛風味 簡單享受' title='單品系列' bgc='#1A1A1A' link='/' />
      </div>
    </>
  );
}
